# -*- coding: utf-8 -*-

s = """
Олег	Зебницкий	oezebnitskiy@edu.hse.ru
Anna	Marakasova	anya.tiva@gmail.com
Михаил	Попов	popovm105@yandex.ru
Владислав	Тушканов	v.tushkanov@outlook.com
Максар	Шипхинеев	mshipkhineev@gmail.com
Екатерина	Шмакова	kat.shmakova@mail.ru
Дина 	Якуб	i.dina@bk.ru
Полина	Тихонова	Tikhonova.polly@mail.ru 
Екатерина	Филиппова	filipv.kate@gmail.com
Борис	Ченкураев	boris_chen@mail.ru
Анна	Кобякова	any.kobiakova@gmail.com
Марина	Волосникова	mvolosnikova@gmail.com
Жамшид	Рузиев	zhzhruziev@edu.hse.ru
Федор	Панов	fkpanov@gmail.com
Дамир	Жадиков	d.zhadikov@gmail.com
Курганский	Дмитрий	mykurgansky@mail.ru
Анастасия	Морозова	Miss.anastasia.morozova@gmail.com
Сойжина	Янгутова	Soighina@mail.ru
Екатерина	Скибина	es_skibina@mail.ru
Anastasiya	Tyurina	nastyurina@gmail.com
Максим	Федоров	uhofedr@gmail.com
Александра	Трифонова 	aleksandra.trif@gmail.com
Артем	Сафонов	Artyom.Safonov@gmail.com
Дмитрий	Станкул	stankuld@gmail.com
Роман	Цуканов	romusello@gmail.com
Антон	Малыгин	Anton_malygin@mail.ru
Юлия	Данилова	yuvdanilova@gmail.com
Кирилл	Рудаков	kirakle1000000@rambler.ru
Арсений	Юнников	exilesoulxx@gmail.com
Лавприт	Сингх	preet.94.kaur@mail.ru
Артем	Семьянов	artyom.semyanov@gmail.com
Константин	Оноприенко	The.konstantin.on@yandex.ru
Pavel	Pereverzev 	Paulyz@mail.ru
Василий	Лукин	vasilij.lukin@gmail.com
Урихан	Санжаева	Urikhan.sanzhaeva@gmail.com
Наталия	Козловская	natalikozlovskaya@gmail.com
Ульяна	Шестакова	Wasp.zsuzsa@gmail.com
Ольга	Рамзайцева	olga.ramz.2012@gmail.com
Олжас	Жиенбай	Zh_olzhas@mail.ru
Никита	Кальянов	nikitakalyanov@gmail.com
Аягоз	Мусабаева	ayagoz.musabaeva@mail.ru
Максим	Карпов	max6482@yandex.ru
Антон	Броиловский	ziliboba753@gmail.com
Артем	Ерохин	ggofat@gmail.com
Егор	Гребенченко	ygarnui@yandex.ru
Руслан	Мусаев	Ruslan.msv@gmail.com
Тагер	Александр	tagsasha@yandex.ru
Евгений	Тушканов	rekrutik@gmail.com
Юлия	Еронина	yu.eronina@gmail.com
Татьяна	Погребняк	zwezwe@mail.ru
Владислав	Ладенков	waryak2012@mail.ru
Евгений	Калиновский	olorin44@mail.ru
Влад	Федоренко	vladfedorenko94@gmail.com
Элен	Маилян 	Mailyan.elen@yandex.ru
Данил	Закирьянов	daniil.zakir@gmail.com
Вера	Беляева	verabel.dev@gmail.com
Игорь	Барановский	baranovskijpost2@yandex.ru
Никита	Гурьянов	neo-prima@yandex.ru
Александр	Бельских	Belskikh.aleksandr@gmail.com
Анна	Пишикина	kirstry@yandex.ru
Николай	Курочка	nikolay.kurochka@gmail.com
Егор	Лабинцев	yegor.labintcev@gmail.com
Николай	Горелов	nickolay1g@yandex.ru
Дмитрий	Парпулов	parpulov.dmitriy@yandex.ru
Максим	Журавлев	Regenmax@mail.ru
Николай	Матхеев	nicola.matheev@gmail.com
Аркадий	Помигуев	od2elf@gmail.com
Сергей	Фомин	sergey.fomin.vl@gmail.com
Александр 	Поплёвко 	Alex.poplyovko@yandex.ru
Dennis	Korotyaev	dennis.korotyaev@gmail.com
Станислав	Ступников	st.stupnikov@gmail.com
Иван	Серов	Ivan.serov.a@gmail.com
Оксана	Шипилова	oxanashipilova@mail.ru
Николай	Кузнецов	shwaige1408@mail.ru
Михаил	Полупанов	albaserpent@gmail.com
Нурлан	Даутов	dautovn@mail.ru
Egor	Kleymenov	K4raul@gmail.com
Александр	Меньщиков	aleksandr.menshchikov@skolkovotech.ru
Константин	Мищенко	konstantin.mischenko@phystech.edu
Виктор	Афанасьев	afanasyev.vik@gmail.com
Юлия	Камшилова	julia.kamshilova@gmail.com
Павел	Геращенко	p.gerashchenko@gmail.com
		
Артем	Сычев	sychev_a_k@mail.ru
Max	Rekunchak	M.Rekunchak@gmail.com
Наталия	Красинская	n.a.krasinskaya@gmail.com
Андрей	Янковский	andrew.a846@gmail.com
Артем	Сычев	sychev_a_k@mail.ru
Валит	Тулебаев	valit.tulebaev@yandex.ru
Олеся	Шарапова	ovsharapova@bk.ru
Андрей	Чернодаров	chernodarov@gmail.com
Илья	Русин	franchb@protonmail.ch
Юлия 	Раскидкина 	ulhen_nvrs@mail.ru
Мария	Зубрихина	m.zubrikhina2014@yandex.ru
Алена	Мельникова	aloha@74.ru
Олег	Сериков	olegserikov@mail.ru
Евгений	Фролов	evfro@live.ru
Денис	Кузнецов	fclmden92@gmail.com
Анна	Балицкая	balitskayaanna@yandex.ru
Полина	Тумольская	vsenichego@gmail.com
Бабайцев	Дмитрий	11keitaro@gmail.com
Артур 	Арйа	artour777.arya1998@gmail.com
Леонид	Екимов	ia3leonid@yandex.ru
Артур	Юмаев	art.yumaev@gmail.com
Андрей	Автомонов	andreybavt@gmail.com
Юлия	Еронина	yu.eronina@gmail.com
Дмитрий	Калашников	kalash2zed@mail.ru
Вячеслав	Матвеев	vmext@mail.ru
Эрик	Габдуллин	thinki@mail.ru
Александр	Сажин	kzsanam@gmail.com
Станислав	Исупов	isypov@inbox.ru
Евгений	Паринов	Evgeny.parinov@frtk.ru
Константин	Барышев	kbaryshev3@gmail.com
Ярослав	Щекатуров 	yaroslavshchekaturov@gmail.com
Сергей	Тильга	tilgasergey@gmail.com
Ибрагим	Алекберов	jklmnopqrstu35@gmail.com
Георгий	Господинов	ga.gospodinov@physics.msu.ru
Марк	Андреев	mark.andreev@gmail.com
Софья	Касацкая 	Sofya.kasatskaya@gmail.com
Николай	Жердев	Nikolay.zherdev@gmail.com
Алла	Федорова	fedorovaad1995@yandex.ru
Азамат	Гафуров	Azamat.Gafurov@gmail.com
Гущин	Кирилл	kirgush@gmail.com
Алексей	Кожевин	allex93@yandex.ru
Даниил	Вълчев	Wolchev.daniel@gmail.com
Анна	Образцова	alcedooo@gmail.com
Дмитрий	Захаров	dizax@mail.ru
Елизавета	Беседина	bio_besedina@mail.ru
Филипп	Гусев	phil.gusev@gmail.com
Антон	Устинов	ustinov.ant@gmail.com
Анна	Куклева	kuklevaanna@gmail.com
Анастасия	Буря	nasburya@gmail.com
Илья	Кирилов	ilyusha.kirillov@gmail.com
Ольга	Перепелкина	Neptizzza@gmail.com
Алдар	Николаев	aldar.nikolaev@gmail.com
Павел	Хомич	osirig@ya.ru
Артур	Александров 	Asdenok@mail.ru
Елена	Кузнецова	Hlnkzntsv@yandex.ru
Алексей	Шариков	Leshafromcheb@mail.ru
Александр	Углов	uglov_alexander@mail.ru
Александр	Буглаков	mojiodec@gmail.com
Павел	Швец	pasher21@ya.ru
Никита	Петтик	pettik@phystech.edu
Александр	Арганаиди	arganaidi@phystech.edu
Даниил	Корбут	korbut.daniel@gmail.com
Роман	Шестаков	urom.mail@gmail.com
Расул	Хасянов 	Khasyanovrr@yandex.ru
		
Дмитрий	Харламов	harldmitr@gmail.com
Даниил	Дмитриев	ocksumoron@yandex.ru
Владислав	Жуков	vladzhukovtirko@gmail.com
Ярослав	Спирин	yar.spirin@gmail.com
Эльнур	Гасанов	gasanov1996@inbox.ru
Илья	Устинов	Fizaxify@gmail.com
Вадим	Плахтинский	plahtinskiy.ve@phystech.edu
Кирилл	Бобырёв	kbobyrev@yandex.ru
Даша	Борисяк	darya.borisyak@gmail.com
Даша	Борисяк	darya.borisyak@gmail.com
Владислав 	Заборовский 	vladzab@yandex.ru
Илья	Беликов	Ilya.i.belikov@gmail.com
Антон	Панкратов	am.pankratov@phystech.edu
Илья	Захаркин	ilyazaharkin@yandex.ru
Оля	Плотникова	plotnikova@phystech.edu
Антон	Ковальков	nishtak97@mail.ru
Евгения	Тверитинова	evgetv28@yandex.ru
Виктор	Мишин	mishinvd@gmail.com
Роман	Ушаков	canorbal@gmail.com
Игорь	Кириченко	i.e.limansky@gmail.com
Охлопков	Даниил	okhlopkov@phystech.edu
Александра 	Шлычкова 	as.darkson@mail.ru
Артем	Куприянов	kupriyanovartem@yandex.ru
Михаил	Аксенов	aksenov@phystech.edu
Арслан	Мазитов	jtks52@gmail.com
Евгения	Ческидова	cheskidova@phystech.edu
Анатолий	Глушенко	glutolik@gmail.com
Дмитрий	Нехаев	nekhaev.d.v@yandex.ru
Никита	Мокров	mokrov.ns@phystech.com
Елена	Иващенко	elenaiv100@gmail.com
Сергей	Колесников	sergey.s.kolesnikov@phystech.edu
Ксюша	Леонтьева	kitnoelka@gmail.com
Николай	Назаров	nazarov_ni@mail.ru
Александр	Сноркин	snorkin@phystech.edu
Александр	Кульков	adamant.pwn@gmail.com
Альберт	Нагапетян	albert.nagapetyan@phystech.edu
Николай	Егоров	nickolayyegorov@gmail.com
Рамиль	Бикбаев	Ramilrbikbaev@gmail.com
Кирилл	Гращенков	kg060296@mail.ru
Екатерина	Гольцова	cache-nez@yandex.ru
Антон	Захаренков	anton.zaharenkov@phystech.edu
Булат	Ниатшин	theairvideo@gmail.com
Артем	Бетлей	betley.artem@phystech.edu
Федор	Стрельцов	sfeaal@gmail.com
Юрий	Валанкин	valankin@gmail.com
Тэмуджин	Манжиков	temudzhin94@gmail.com
Владимир	Канаев	kanaev@phystech.edu
Владислав	Комаров	v.kom91@gmail.com
Талгат	Сапаров	saparov2130@gmail.com
Глеб	Синяков	sinyakov@phystech.edu
Ярослав	Черепанов	yaroslav.cherepanov@gmail.com
Владислав	Матюхин	vladmatyukh@gmail.com
Гузовский	Евгений	gendal4@yandex.ru
Вадим	Лукманов	vadiklukmanov@yandex.ru
Сергей	Иванычев	sergeyivanychev@gmail.com
Роман	Ануфриев	roman.anufr@gmail.com
Евгений	Брицын	Ebritsyn@gmail.com
Alexey	Timofeev	mail.timofeev.av@gmail.com
Елена	Жердева	lena-zherdeva@mail.ru
Александр	Гаев	Krock21rus@gmail.com
Даниил	Чернявский	danchern97@mail.ru
Илья	Гридасов	Ilya151098@yandex.ru
Марк	Потанин	mark.potanin@phystech.edu
Анастасия 	Коробкина 	styuu19@gmail.com
Екатерина 	Носикова 	katia.nosikova@mail.ru
Павел	Ляхов	pavel.lyakhov@phystech.edu
Александр	Смоляков	sashasmolykov@gmail.com
Рустем	Ахияров	akhiarov@gmail.com
Жакшылык	Нурланов 	jaksha97@mail.ru
Евгений	Суханов	echelon2@mail.ru
Иван	Едигарьев	edigaryev.ig@phystech.edu
Антон	Нехаев	antonnekhaev@gmail.com
Артем	Савельев	art290790@yandex.ru
Андрей	Паутов	Pautov@phystech.edu
Михаил	Перельштейн	mikaosnova@gmail.com
Руслан	Канзепаров	Kanzeparov@yandex.ru
Артем	Лукоянов	lukoyanov.as@phystech.edu
Ахмедхан	Шабанов 	sha-ahan@yandex.ru
Тамаз	Гадаев	Gadaev.tamaz@gmail.com
Егор	Шульгин	dwarfegor@yandex.ru
Андрей	Каменев	kamenev.andrew@gmail.com
Игорь 	Слободсков 	Igor.slobodskov@phystech.edu
Сергей	Колченко	kolchenkosergey@gmail.com
Антон	Кутафин	akutafin@gmail.com
Булат	Якупов	yakupov.bulat@gmail.com
Стас	Округ	alekstanok@yandex.ru
Артем	Меринов	artemmerinov@yandex.ru
Максим	Савельев	Maksdizzy@gmail.com
Пётр	Болотин	petr.bolotin@phystech.edu
Олег	Дробот	oleg.drobot@frtk.ru
Дамир	Салахутдинов	sherbet.box@mail.ru
Игорь	Матвеев	igor.matveev@phystech.edu
Карина	Самигуллина	samigulina.ki@phystech.edu
Артем	Потапов	artem.potapov@frtk.ru
Саша	Кулакова	walrushere@gmail.com
Дарина	Двинских	dviny.d@yandex.ru
		
Федор	Ерин	fedor.erin@frtk.ru
Владислав	Смирнов	smirnovvlad2103@gmail.com
Александр	Мацун	ienjoyeatingcorpses@gmail.com
Анастасия	Евтеева	elis24.96@mail.ru
Виктор	Ахлынин	ahlininv@gmail.com
Денис	Антипин	deantipin@frtk.ru
Руслан	Рахимов	r.rakhimov@my.com
Владимир	Баймаков	baymakov1997@mail.ru
Денис	Кудяков	kudyakov.denis@yandex.ru
Федор	Киташов	fedor.kitashov@phystech.edu
Артём	Аверьянов	Averyanovartem@mail.ru
Павел	Цай	tsay.pa@phystech.edu
Светлана	Субботина	subbotina@phystech.edu
Сергей	Масленников	sergey.maslennikov@phystech.edu
Павел	Левдик	levdik.pavel@gmail.com
Назарий	Тупица	two_nazya@mail.ru
Кирилл	Талалаев	kirill.mipt2013@gmail.com
Искандер	Накипов 	iskander.sych@gmail.com
Павел	Курилович	kurilovichpd@gmail.com
Владислав	Курилович	vladislav.kurilovich@gmail.com
Илья	Белкин	ilya.belkin-trade@yandex.ru
Юлия	Белостоцкая	belostotskaya@phystech.edu
Павел	Захаров	paltoszaharov@yandex.ru
Илья	Гуков	ilyagukov@list.ru
Юрий	Морозов	yur.yhse@gmail.com
Дмитрий	Ефимов	sikirr@gmail.com
Яна	Долюк	yana.dolyuk@gmail.com
Филипп	Никитин	filipp.nikitin.96@gmail.com
Анна	Кузьмина	anna.k.b@yandex.ru
Александр	Захаров	aleksandr.zakharov@phystech.edu
Дарья	Зверева	zverevads@gmail.com
Михаил	Усвяцов	miha-usv@yandex.ru
Глеб	Моргачев	morgachev.gi@phystech.edu
Алексей	Казаков	kazakov1501@gmail.com
Антон	Смердов	neonx11ant@gmail.com
Денис	Калмыков	denis.kalmykov@phystech.edu
Николай	Карпачёв	n.karpachov@gmail.com
Любовь	Камалдинова	kamaldinova@phystech.edu
Анастасия	Тимошенко	timoshenkonas@gmail.com
Хатыпов 	Семен 	 SemkaHatypov@gmail.com 
Хуррам	Пиров	Khurram.pirov@phystech.edu
Алексей	Чекушкин	alesha148@gmail.com
Айрат	Мулюков	mulyukov.al@phystech.edu
		
Александр	Рубашевский	sasha-rubashevskiil@mail.ru
Алина	Егорова	egoro.lina@gmail.com
Дмитрий	Грязин	Gdime@yandex.ru
Валерия	Абрагимович	abragimovich-lera@rambler.ur
Семен	Федотов	simon23rus@gmail.com
Михаил	Немилов	xmanatee.one@gmail.com
Валерий	Умеренков	umerenkov@phystech.edu
Валерий	Умеренков	umerenkov@phystech.edu
Ирина	Дмитриева	atlantie@yandex.ru
Юсуф	Худайбердиев 	yus-uf96@mail.ru
Кирилл	Мельников	nepishiemy@yandex.ru
Сергей	Володин	sergei.volodin@phystech.edu
Ольга	Горбачева	olga.gorbacheva@phystech.edu
Максим	Степкин	maxim.stiopkin@yandex.ru
Артем	Ребриков	Artemrebrikov@gmail.com
Никита	Самсонов	nikita.samsonov@phystech.edu
Михаил	Коптев	m.koptev@outlook.com
Андрей	Черников	andreycher@yandex.ru
Дмитрий	Доронин	dmitr-doronin@yandex.ru
Александр	Михалевич	alex.mikhalevich@gmail.com
Юлия	Семавина 	semavina57@yandex.ru
Анна	Елизарова	mdihcroe@gmail.com
Людмила	Разумовская 	kudriashka07mail. ru
Анастасия	Красавина	ashiya-hime@yandex.ru
Ирина	Пугаева	pugaevaarina@gmail.com
Александр	Кильянов	kaa.kilyanov@gmail.com
Владимир	Кондратенко	vladimir.kondratenko@phystech.edu
Петр	Курапо	petr.kurapov@gmail.com
Иван	Коваль	ivan.koval@icloud.com
		
Салех 	Гаджибеков 	salgasd@gmail.com
Сергей	Соловьев	fjdiod@gmail.com
Ярослав	Коноплёв	yaroslav.konoplev@phystech.edu
Кирилл	Скорняков	kirill.skornyakov@phystech.edu
Дмитрий	Радкевич	dmitrii.radkevich@phystech.edu
Роман	Доронин	roman.a.doronin@phystech.edu
Mark	Boch	mark.mipt@yahoo.com
Александр 	Волков 	aleksandr.o.volkov@phystech.edu
Александр	Щербина	sascherbina@gmail.com
Всеволод	Курушин	v.a.kurushin@gmail.com
Александр	Селютинё	zlougamer@gmail.com
Александр	Северинов	aleksandr.severinov@phystech.edu
Глеб	Фильков	filcom.gl@gmail.com
Андрей	Потапов	andrpotapov@gmail.com
Даниил	Поляков	daniil.polyakov@phystech.edu
Андрей	Сафронов	safrandrey@gmail.com
Анастасия	Стрельникова	Strelnikova.a.m@gmail.con
Андрей	Киселев	kiselev1189@gmail.com
Регина	Гареева	gareeva.reginka@yandex.ru
Андрей	Жерихов	adaico.z@gmail.com
Александр	Кузнецов	alex.kuznetsov87@gmail.com
Владислав	Бояджи	Vladislav.boyadzhi@gmail.com
Владимир	Ивашкин	vladimir.ivashkin@phystech.edu
Максим	Калацкий	kalatzky@yandex.ru
Дарья	Мамаева	mamaevads@gmail.com
Иван	Гончар	ivan.gonchar@phystech.edu
Данил	Сметанев	DANIL-smetanev@yandex.ru
Андрей	Гагин	grifonne@inbox.ru
Екатерина	Адаменко	katya.adamenko@gmail.com
Дмитрий	Кузьмичев	kuzmichevdima95@gmail.com
Ксения	Колесник	kolesniksenya@yandex.ru
Борис	Широких	bg.dustpelt@gmail.com
Евгений	Смирнов	evgeny97.ru@gmail.com
Григорий	Ковтун	mrgrigorii@mail.ru
Анна	Смагина	a.smagina1995@gmail.com
Данияр	Аманбаев	amanbay16@mail.ru
Анна	Данилова	dania.91@mail.ru
Дмитрий	Шапошников	shaposhnikov@phystech.edu
Алина	Самохина	linasamokha@gmail.com
Леонид	Литовченко	litleo@mail.ru
Илья	Гусев	ilya.gusev@phystech.edu
Дарья	Михайлова	darya.mikhailova@phystech.edu
Анастасия	Грачёва	nastya.vcg@gmail.com
Artur 	Mindiiarov 	mindartyr@mail.ru
Алёна	Егорова	ladyae@ya.ru
Эмиль	Яковлев	emilyakowlew1@gmail.com
Михаил	Федотов	mihailfedotow@yandex.ru
Джамиль	Закиров	djamilzak@gmail.com
Руслан	Ковалёв	velavokr@yandex-team.ru
Сергей	Губанов	GubSergEvg@yandex.ru
Филипп	Петров	Fileasfog931997@gmail.com
Михаил	Мартинсон	Mmartinson@yandex.ru
Артем	Ломов	artem-lomov@yandex.ru
Игорь	Новиков	nie1997@yandex.ru
Артём	Чащин	chashchinartyom@yandex.ru
Владимир	Дохолян	Dokholyan97@mail.ru
Александр	Лактионов	lokotochek@gmail.com
Константин	Рудаков	karudakov@gmail.com
Кирилл	Тушин	kirya.tushin1@yandex.ru
Марк	Потанин	mark.potanin@phystech.edu
Илья	Компаниец	worchun@list.ru
Кирилл	Буряк	kirill.buryak@phystech.edu
Ирина	Нифантова	nifantova98@gmail.com
Владислав	Михайлов	mihailov_@bk.ru
Алексей	Миронов	
павел	калошин	kaloshinpavel@gmail.com
Екатерина	Стасевич	kankan1010@yandex.ru
Иван	Наседкин	ivan_nasedkin97@mail.ru
Никита 	Дурасов 	yassnda@gmail.com 
Maxim	Kushniruk	maxim.kushniruk@yandex.ru
Дмитрий	Мыльников	altsiona@yandex.ru
Николай	Шувалов	shuvalovnickolay@gmail.com
Софья	Боровикова	Sonicbor@yandex.ru
Артем 	Соломатин 	artemsolomatin19@mail.ru 
Александр	Бойко	boykodjs4@ya.ru
Леонид	Каличкин	leonid.kalichkin@phystech.edu
Александра	Миночкина	minochkina.a@gmail.com
Артем	Лян	tntlgf93@mail.ru
Артем	Гец	agets@inbox.ru
Сергей	Гвоздарёв	gvozdarev.sa@gmail.com
Ирина	Маликова	malikova.ie@phystech.edu
Екатерина	Архипова	arkhiekaterina@gmail.com
Александр	Кравцов	alexander.kravtcov@gmail.com
София	Подобедова	sofia.podobedova@gmail.com
Даниил	Паринов	daniil.parinov@phystech.edu
Артур	Фаттахов	fattahov.ao@phystech.edu
Борис	Галицкий	galickiiboris@mail.ru
Павел	Грамович	pavelgramovich@mail.ru
Айваз	Давлетханов 	davaizilg@gmail.com
Александр	Парубченко	parubchenko@phystech.edu
Дарья	Фокина	dasha.fokina@phystech.edu
Игорь	Мусинов	igor.musinov@phystech.edu
Евгений	Егоров	evgeniy.eg1@mail.ru
Иван	Голованов	ivan.golovanov@phystech.edu
Владимир	Бусовиков	treonon38@mail.ru
Юлия	Пинина	jei.pi.em@gmail.com
Владимир	Литвиненко	vladimir.litvinenko.1997@gmail.com
Александр	Рогозин	alex_rogozin12@mail.ru
Игорь	Прусов	prusovigor@gmail.com
Катугина	Татьяна	Katu-tatyana@yandex.ru
Михаил	Вилкин	mkvilkin@gmail.com
Екатерина	Багаева	ebagaeva@nes.ru
Алексей	Петрянкин	0nf0r0l@gmail.com
Дмитрий	Платов	platovd@gmail.com
Ефим	Крохин	efim.krohin@frtk.ru
Сергей	Рожнев	rozhnevsv@gmail.com
Павел	Смелов	pavsmel@mail.ru
Ангелина	Коваленко	Angelina.kovalenko@phystech.edu
Сергей	Никифоров	Sergeynikiforov761@gmail.com
Сергей	Шачнев	shachnevs16@gmail.com
павел	губко	gubkopaul@yandex.ru
Анна	Медведева	medanya@inbox.ru
Дмитрии	Кулагин	dk@aha.ru
Александр	Медведев	alexandermed@mail.ru
Аркадий	Баранок	a.baranok@yandex.ru
Аня	Ершова 	anna.ershova1@yandex.ru 
Денис	Копосов	denis.koposov@phystech.edu
Игорь	Хромов	hromov.igor@gmail.com
Алексей	Ершов 	Wanko@list.ru
Валерий	Конычев	valerakonychev@gmail.com
Евгений	Васильев	evgeniy_vasilev_97@bk.ru
Руслан	Сабиргалиев	ruslan.sabirgaliev@phystech.edu
Михаил	Анухин 	botaymath@gmail.com
Антон	Никишин	nikanton@live.ru
Игорь	Легезо 	igor.legezo@mail.ru
Сергей 	Михалёв	mr.tyborg@yandex.ru
Аня	Ершова 	anna.ershova1@yandex.ru 
Вера	Исламова	Islamovaveramail@gmail.com
Александр	Иванов	Alexandr.ivanov2108@gmail.com
Михаил	Чесноков	mikhail.chesnokov@phystech.edu
Руслан	Янбарисов	polisusl@mail.ru
Раиса	Рябинина	raya.orlova.98@mail.ru
Даниил	Петров	selfdestruct@bk.ru
Павел	Максимочкин	maksimochkin.pavel@frtk.ru
Юсуф	Худайбердиев 	Yus-uf96@mail.ru
Даниил	Емцев	daniil.emcev.ru@yandex.ru
Дмитрий	Николаев	etsu.nikolaev@gmail.com
Артем	Хохлов	artem.khokhlov@phystech.edu
Лев	Островский	lev_sky@mail.ru
Валентин	Родионов	valientin-rodionov@mail.ru
Владислав	Пеньковский	vladpenkovskiy@yandex.ru
Георгий	Чермянин	chermyanin@phystech.edu
Валентин	Родионов 	valientin-rodionov@mail.ru
Дмитрий	Никифоров	dmitryn10@mail.ru
Илья 	Кремянский	kremynskiy@mail.ru
Марсель	Валеев	mar_tek@mail.ru
Yan	Egorov	egorov.yan@gmail.com
Руслна	Сулейманов	ryseek1@gmail.com
Дмитрий	Ефимов	sikirr@gmail.com
Антон	Морозов	moranton@mail.ru
Олег	Сериков	olegserikov@mail.ru
Антон 	Морозов	moranton@mail.ru
Михаил	Евсеев	evseev.michail@gmail.com
Игорь	Козловский	igor.kozlovskiy@phystech.edu
Роман	Гончар	roman.gonchar@phystech.edu
Игорь	Трушкин	igor.trushkin.1991@yandex.ru
Илья	Романенко	ilya.i.romanenko@yandex.ru
Кирилл	Муравьев	kirill.mouraviev@yandex.ru
Петр	Баранов	pbaranov91@gmail.com
Александр	Парубчишин	alex.paru95@gmail.com
Эмиль	Закиров	bonlimezak@gmail.com
Диана	Хамматова	khammatova.diana@ya.ru
Андрей	Мальцев	maltsev.ai96@gmail.com
Даниил	Симонов	ufr3108@mail.ru
Арсен	Абдулхамидов	Arsen.a13.1445@mail.ru
Павел	Рейдман	preidman@gmail.com
Анастасия	Илюхина	Nastuxa-278@yandex.ru
Дмитрий	Наумов	duman.nau@yandex.ru
Анастасия	Баяндина	anast.bayandina@gmail.com
Анатолий	Потапов	anatolii.s.potapov@gmail.com
Денис	Марченко	den.mar@mail.ru
Юлия	Вакуленко	vjulia94@gmail.com
Евгений	Гадыльшин	loinelyhorse04@gmail.com
Дмитрий	Бабайцев	11keitaro@gmail.com
Антон	Трубаков	antontrubakov@gmail.com
Алла	Федорова 	fedorovaad1995@yandex.ru
Константин	Соболев	sobokonst@gmail.com
Дмитрий	Котлуков	Dkotlukov@gmail.com
Руслан	Гилязутдинов	gilyazutdinov@phystech.edu
Мария	Пашкова	pashkoffhouse@gmail.com
Anton	Lukashchuk	anton.lukashchuk@skolkovotech.ru
Никита	Уваров	dragonicthebest@gmail.com
Андрей	Паутов	pautov@phystech.edu
Сергей	Марченко	acmilan.1899@mail.ru
Карина	Усманова	usmanovakr96@gmail.com
Артем	Петров	petrov.still@gmail.com
Никита	Федоров	fedorov@webergreen.com
Анна	Карасик	aniakarasik@yandex.ru
Дмитрий	Бугаков	bugakov.dima@gmail.com
Арсен	Абдулхамидов	arsen.a13.1445@mail.ru
Дмитрий	Карелин	Dkarelin314@yandex.ru
Станислав	Драчевский	drchvsk@gmail.com
Дарья	Пугачёва	sedyakina@phystech.edu
Роман	Колесников	natrit@mail.ru
Алексей	Болдырев	boldyrevside@gmail.com
Нарек	Геворгян	mr.gevorgyan10@gmail.com
Оксана	Шипилова	oxanashipilova@mail.ru
Александра	Гуляева	al.goulieva@gmail.com
Игорь	Остапенко	mrua@yandex.ru
Федор	Игнатов	ignatov.fedor@gmail.com
Олег	Бусловский	buslovskii@phystech.edu
Евгений	Станчин	zhenystanchin@mail.ru
Харитонов 	Иван	tibboh69@mail.ru
Павел	Лысенко	pavel.lysenko@frtk.ru
Александр	Иванюшенко	aleks.ivanyshenko@gmail.com
Роберт	Уде	robert.udeh@gmail.com
Даниил	Выговский	mdani.vygovsky@gmail.com
Екатерина	Чуйкова	Chuikova.e.e@yandex.ru
Вишневский	Иван	vishnevskyivan_1995@mail.ru
Надежда	Гапеева	gapeevanad@gmail.com
Азиза	Калмасова	kasuka31to12mikasa@gmail.com
Руслан	Насртдинов	nasertrus@mail.ru
Дарья	Романовская	romanovskaya@phystech.edu
Татьяна	Савельева	savelievatanyya@gmail.com
Александр	Борзилов	alex-borz@yandex.ru
Владислав 	Нескорнюк	vlnec@yandex.ru
Василий	Молотов	vasiliy.molotov@gmail.com
Даниил	Саргин	sargin@phystech.edu
Андрей	Нестеров	andrey.nesterov@phystech.edu
Михаил	Евсеев	evseev.michail@gmail.com
Дмитрий	Акшинцев	akshincevdo@gmail.com
Альфия	Мухамадиева	muhamadieva.alfiya@mail.ru
Дмитрий	Беляев	dmitry.bl.5967@gmail.com
Павел	Шаповалов	shapovalov-paul@yandex.ru
Аркадий	Савицкий	arkosav@gmail.com
Арсений	Савицкий	sao1992@mail.ru
Игорь	Красовский	igor.krasovskii@phystech.edu
Григорий	Ганкин	gregorian21@yandex.ru
Евгений	Жуков	jookovjook@gmail.com
Ольга	Локотилова	lokotilova@phystech.edu
Владимир	Сидоров	vladimir.sidorov@phystech.edu
Ирина	Голощапова	edgy1969@gmail.com
Камиль	Бадрутдинов	kamilB97@yandex.ru
Ольга	Панфёрова	panferova.olga@gmail.com
Анастасия	Кулакова	nastyakul1997@gmail.com
Виталий	Емельянов	emelianov.vitaly@yandex.ru
Валерия	Вербицкая	valverbitskaya@ya.ru
Яна	Ульяненко	ulfam@yandex.ru
Мила	Шарманова	mila.sharmanova@gmail.com
Матасова	Елена	mataelle@gmail.com
Владислав	Ладенков	waryak2012@mail.ru
Дмитрий	Паршин	parshin@phystech.edu
Мирослав	Антонович	antonovich.miroslav@gmail.com
Vladimir	Ershov	ershov-v@mail.ru
Антон	Протопопов	dretox@mail.ru
Алексей	Курочкин	al.kurochkin93@gmail.com
Анастасия	Сторожева	storozhewa.anastasya@yandex.ru
Александр	Белов	a.belov@phystech.edu
Султан	Исалы	isaly@phystech.edu
Дмитрий	Абулханов	heapnhash@gmail.com
Вадим	Варнавский	vadim.varnavskij@frtk.ru
Дмитрий	Ковалев	Dakovalev1@mail.ru
Даниил	Воробьев	d-9797@mail.ru
Денис	Смирнов	Denis.smirnov.b@gmail.com
Артем	Анисимов	a-anisimov@phystech.edu
Павел	Гавриленко	gavrilenko@phystech.edu
Харитонов	Иван	tibboh69@gmail.com
Елизавета	Федорова	fedorova-elizaveta@yandex.ru
Андрей	Поповкин	andreypopovkin@yandex.ru
Григорий	Соболь	grishasobol@mail.ru
Лыков	Данил	lkv97dn@gmail.com
Кирилл	Голубев	kot.duh.ogna2@gmail.com
Ирина	Сигарёва	irina.sigareva@mail.ru
Дмитрий	Макаренко	devjiu@gmail.com
Леонид	Кальницкий	leoni.yurevic@gmail.com
Оксана	Мигдаль	migdal@phystech.edu
Тимур	Абди	timurabdi@gmail.com
Иван	Харитонов	ipkharitonov@gmail.com
Илья	Барышников	firesonics@yandex.ru
Карим	Киреев	Kireevkarim@yandex.ru
Евгений	Румынский	erumynskiy@gmail.com
Владислав	Андрияшен	animals_ua@ukr.net
Герман	Чесноков	geryc2008@yandex.ru
Дмитрий	Курганский	mykurgansky@mail.ru
Василий	Рязанов	vasyarv@mail.ru
Василий	Виноградов	VinogradovVI61@gmail.com
Евгений	Рубаненко	rubanenko.em@phystech.edu
Софья	Потапова	sofiapotapova95@mail.ru
Елсуков	Владислав	vladislav.elsukov@phystech.edu
Александр	Белов	a.belov@phystech.edu
Кирилл	Кочнев	Kikochnev@yandex.ru
Александр	Мищенко	5740235@gmail.com
Валерий	Медведев	vmedvedev24@gmail.com
Владимир 	Максименков 	wladimir-maks@yandex.ru
Денис	Горев	eveleech@gmail.com
Егор	Фирсов	egor-fi@yandex.ru
михаил	Пачин	9777953667@mail.ru
Халид	Мустафин	khalid.mustafin@yandex.ru
Михаил	Куренков	kurenkov1995@mail.ru
Леонид	Пугачёв	puleon@mail.ru
Анастасия	Виденеева	nastya.videneeva@gmail.com
Максим	Бородин	borodin.ms@phystech.edu
Николай	Дзичковский	mikola6@yandex.ru
Мария	Малярова	malyarovamv@sgu.ru
Григорий	Шабалов	gregory.shabalov@gmail.com
Александр	Боймель	aleksandr.boymel@phystech.edu
Самал	Кубентаева	samalsamal2@mail.ru
Алина	Канзафарова	kanzelina@rambler.ru
Анатолий	Лбов	tol9nos@gmail.com
Андрей	Комендантян	komendantyan@gmail.com
Евгений	Левин	levin.eugen@gmail.com
Михаил	Василенко	mishanja_96@inbox.ru
Дмитрий	Иноземцев	izyumchik09@mail.ru
Светлана	Черкесова	s-vet_a@mail.ru
Александр	Дериглазов	deriglazov@phystech.edu
Игорь 	Шохрин 	igor.shokhrin@gmail.com 
Вячеслав	Иванов	ivanov.vv@phystech.edu
Надежда 	Зуева	zueva.nn@phystech.edu
Маша	Власенок 	mashlosenok@gmail.com
Алексей	Князев	alexkniazev@gmail.com
Александр	Неверов	neverovmipt@gmail.com
Илья	Игашов	igashov.i@yandex.ru
Кирилл	Михайлович	korotkovkm@gmail.com
Бакберген	Жуматаев	bzhumataev94@gmail.com
Игорь	Юсупов	justedeboute31@gmail.com
Иракли	Микаберидзе	hse@gos.moscow
Daniil	Okhlopkov	okhlopkov@phystech.eud
Михаил	пачин	mikhail.pashcin@gmail.com
Кирилл	Шевкунов	howtodo@ya.ru
Денис	Дворянов	spectralden@mail.ru
Сергей 	Гуртовой	skrafy@bk.ru
Олеся	Алтунина	altunina@phystech.edu
Владимир	Аксёнов	vlaxen@gmail.com
Алексей	Орлов	lexx.orlov@gmail.com
Агапов	Дмитрий	agapovdmitry@gmail.com
Грязнов	Михаил	mihaha_9@mail.ru
Константин	Жердев	kzherdev@gmail.com
Денис	Смирнов	armagy@gmail.com
Николай	Карташов	nick160690@gmail.com
Фёдор	Минькин	fedor.minkin@phystech.edu
Федор	Фомичев	fedor.fomichev@phystech.edu
Артем	Юрьевич	arktik940121@mail.ru
Михаил	Пачин	irdav2007@rambler.ru
Дмитрий	Агапов	Agapovdmitry@gmail.com
Павел	Клишин	pklishin@gmail.com
Артем	Воробьев	Vorobev@phystech.edu
Акбар	Оразбаев	akbarsky93@mail.ru
Данил	Лыков	lkv97dn@gmail.com
Михаил	Грязнов	mihaha_9@mail.ru
Олег	Мымрин	mymrin.oleg@gmail.com
"""

l = []
for x in s.split("\n"):
	x = x.strip().decode('utf-8')
	if x != '':
		try:
			tokens = x.split('\t')
			l.append({
				'name': tokens[0],
				'surname': tokens[1],
				'email': tokens[2].lower()
			})
		except IndexError:
			pass

import json

with open('all_students.json', 'w') as f:
	json.dump(l, f, indent=4)